// <auto-generated />
using Camping.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Camping.Migrations
{
    [DbContext(typeof(CampingDbContext))]
    partial class CampingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Camping.Model.ProductModel.Product", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.Property<string>("Image");

                    b.Property<string>("Name");

                    b.Property<decimal>("Price");

                    b.Property<string>("Sku");

                    b.HasKey("ID");

                    b.ToTable("Inventory");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Description = "This is a backpack",
                            Image = "/Assets/backpack.jpg",
                            Name = "BackPack",
                            Price = 30m,
                            Sku = "BS6000"
                        },
                        new
                        {
                            ID = 2,
                            Description = "This is a sleeping bag",
                            Image = "/Assets/sleepingbag.jpg",
                            Name = "Sleeping Gear",
                            Price = 80m,
                            Sku = "BS6001"
                        },
                        new
                        {
                            ID = 3,
                            Description = "Can be used to help see",
                            Image = "/Assets/flashlight.jpg",
                            Name = "FlashLight",
                            Price = 30m,
                            Sku = "BS6002"
                        },
                        new
                        {
                            ID = 4,
                            Description = "Can be used to help see",
                            Image = "/Assets/lantern.jpg",
                            Name = "Lantern",
                            Price = 40m,
                            Sku = "BS6003"
                        },
                        new
                        {
                            ID = 5,
                            Description = "A pair of gloves",
                            Image = "/Assets/gloves.png",
                            Name = "Gloves",
                            Price = 80m,
                            Sku = "BS6004"
                        },
                        new
                        {
                            ID = 6,
                            Description = "Water shedder",
                            Image = "/Assets/rainshell.jpg",
                            Name = "Rain shell",
                            Price = 20m,
                            Sku = "BS6005"
                        },
                        new
                        {
                            ID = 7,
                            Description = "luis and clarks map",
                            Image = "/Assets/map.jpg",
                            Name = "Map",
                            Price = 10m,
                            Sku = "BS6006"
                        },
                        new
                        {
                            ID = 8,
                            Description = "Fire starting kit",
                            Image = "/Assets/flint.jpg",
                            Name = "Flint and Steel",
                            Price = 10m,
                            Sku = "BS6007"
                        },
                        new
                        {
                            ID = 9,
                            Description = "Baseball cap",
                            Image = "/Assets/hat.jpg",
                            Name = "Hat",
                            Price = 50m,
                            Sku = "BS6008"
                        },
                        new
                        {
                            ID = 10,
                            Description = "Tracking device",
                            Image = "/Assets/gps.jpg",
                            Name = "Gps",
                            Price = 200m,
                            Sku = "BS6009"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
